---
application:
  name: "image-uploader"
  project: "Image-Uploader-API"
  organization: "QoveryCommunity"
routers:
- name: "main-image-uploader"
  routes:
  - application_name: "image-uploader"
    paths:
    - "/*"
